sonar.sourceEncoding=UTF-8
sonar.sources=app,components,db,lib
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx
sonar.exclusions=.github/**,node_modules/**,public/**
sonar.typescript.tsconfigPath=tsconfig.json