import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

const { clerkProviderMock } = vi.hoisted(() => ({
    clerkProviderMock: vi.fn(),
}));

vi.mock("next/font/google", () => ({
    Geist: () => ({ variable: "font-geist-sans" }),
    Geist_Mono: () => ({ variable: "font-geist-mono" }),
}));

vi.mock("@clerk/nextjs", () => ({
    ClerkProvider: ({ children, ...props }: React.PropsWithChildren<Record<string, unknown>>) => {
        clerkProviderMock(props);

        return (
            <div data-testid="clerk-provider">{children}</div>
        );
    },
    SignInButton: ({ children }: { children: React.ReactNode }) => (
        <div data-testid="sign-in-button">{children}</div>
    ),
    SignUpButton: ({ children }: { children: React.ReactNode }) => (
        <div data-testid="sign-up-button">{children}</div>
    ),
    Show: ({ children }: { children: React.ReactNode }) => <>{children}</>,
    UserButton: () => <div data-testid="user-button">User</div>,
}));

import RootLayout, { metadata } from "@/app/layout";

describe("RootLayout", () => {
    it("exports the app metadata", () => {
        expect(metadata).toEqual({
            title: "Create Next App",
            description: "Generated by create next app",
        });
    });

    it("renders auth controls and children within the layout shell", () => {
        clerkProviderMock.mockReset();

        const layout = RootLayout({
            children: <main>Page Content</main>,
        });

        expect(layout.props.lang).toBe("en");
        expect(layout.props.className).toContain("font-geist-sans");
        expect(layout.props.className).toContain("font-geist-mono");

        render(layout.props.children.props.children);

        expect(screen.getByTestId("clerk-provider")).toBeInTheDocument();
        expect(clerkProviderMock).toHaveBeenCalledWith({
            signInFallbackRedirectUrl: "/dashboard",
            signUpFallbackRedirectUrl: "/dashboard",
        });
        expect(screen.getByTestId("sign-in-button")).toBeInTheDocument();
        expect(screen.getAllByTestId("sign-up-button")).toHaveLength(1);
        expect(screen.getByTestId("user-button")).toBeInTheDocument();
        expect(screen.getByText("Page Content")).toBeInTheDocument();
        expect(screen.getByRole("button", { name: "Sign in" })).toBeInTheDocument();
        expect(screen.getByRole("button", { name: "Sign up" })).toBeInTheDocument();
    });
});